class Board
  attr_reader size: Integer

  attr_reader cells: Array[Array[String]]

  def initialize: (Integer size) -> void

  def create_board: () -> Array[Array[String]]

  def show_on_center: (String text) -> void
end