class Board
  attr_reader size: Integer

  attr_reader cells: Array[Array[String]]

  def initialize: (size: Integer) -> void

  def create_board: () -> Array[Array[String]]

  def reset: () -> void

  def show_on_center: (text: String) -> void
end