module GameState
  NONE: 0

  IN_GAME: 1

  GAME_OVER: 2

  GAME_QUIT: 3
end

class Game
  attr_reader board: Board

  attr_reader snake: Snake

  attr_reader food: Food

  def initialize: (board_size: Integer?, snake_size:Integer?) -> void

  def run: () -> void

  def show_exit_screen: (text: String) -> void

  def show_start_screen: () -> void

  def show_game_screen: () -> void

  def update: () -> void

  def draw: () -> void

  def input: () -> void

  def update_snake: () -> void

  def check_if_snake_met_wall: () -> void

  def check_if_snake_ate_food: () -> void

  def check_if_snake_ate_itself: () -> void
end
