class Snake
  attr_reader size: Integer

  attr_reader direction: Symbol

  attr_reader position: Array[Integer]

  attr_reader parts: Array[Array[Integer]]

  def initialize: (board_max_x: Integer, board_max_y: Integer, size: Integer) -> void

  def create_snake: () -> void

  def set_random_position: (board_max_x: Integer, board_max_y: Integer) -> void

  def head: () -> Array[Integer]

  def body: () -> Array[Array[Integer]]

  def grow: () -> void

  def set_head: (index: Integer, value: Integer) -> void

  def turn: (key_code: String) -> void

  def move: () -> Array[Integer]
end
